### ISSUE TITLE
Spreads!

### ISSUE THREAD

**Issue by diceroll123** [dvoiss/literallytoast#2]
To add to #1, howsabout some...

* Jelly
* Peanut Butter
* Regular butter (probably better off NOT implementing [ButterKnife](https://github.com/JakeWharton/butterknife) for this)
* Marmite for those in the upside-down 🙃

**Comment by dvoiss** [comment]
Great suggestions!

Marmite? 🤢

**Comment by diceroll123** [comment]
Never had it! I hear mixed things though.
